language: java
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
services: mysql
before_script:
  - mysql -e 'create database remitt;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -utravis -ppassword -e 'SOURCE sql/ddl.sql'
