language: java
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
services: mysql
sudo: false
before_script:
  - mysql -e 'create database remitt;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='travis';\nGRANT ALL ON remitt.* TO travis@localhost;\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -utravis -ppassword remitt -e 'SOURCE sql/ddl.sql'
