#!/bin/sh -e
#
#	$Id$
#	$Author$
#

PROG=remitt
CFG=/etc/${PROG}/${PROG}.conf
PKG=${PROG}

# DEBCONF_DEBUG=developer

RemittGetOption() {
    sed -e "s/[#;].*//"          \
        -e "/^[[:space:]]*$/d" ${CFG}  | \
    perl -ne "\$flag=0; while ( <> ) { 
                if ( \$flag==1 && /$2\s+=\s+(\w+)/ ) { print \$1; exit; } ;
                if ( /$1/ ) { \$flag=1; }
	      }" 
}

. /usr/share/debconf/confmodule
db_version 2.0

if [ -e ${CFG} ]; then
   # if config file exists, read values and set debconf database accordingly
   # to keep user defined values
   ClientURL=`RemittGetOption client url`
   [ -s ${ClientURL} ] && db_set ${PKG}/clienturl $ClientURL
   ClientUsername=`RemittGetOption client username`
   [ -s ${ClientUsername} ] && db_set ${PKG}/clientusername $ClientUsername
   ClientPassword=`RemittGetOption client userpassword`
   [ -s ${ClientPassword} ] && db_set ${PKG}/clientpassword $ClientPassword
fi

db_input medium ${PKG}/clienturl  || true
db_input medium ${PKG}/clientusername  || true
db_input medium ${PKG}/clientpassword  || true
db_go || true

